# Generated by Django 5.2.8 on 2025-11-24 12:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=type, max_length=50, null=True, verbose_name='Full Name')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('role', models.CharField(choices=[('admin', 'SuperAdmin'), ('student', 'Student')], default='student', max_length=10, verbose_name='Role Name')),
                ('is_active', models.BooleanField(default=False)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_status', models.BooleanField(default=False)),
                ('otp_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='/profile/image/1.jpg', null=True, upload_to='profile/image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Profile Image')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserWhitelistTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fingerprint', models.CharField(default='e99a18c428cb38d5f', max_length=64, unique=True, verbose_name='Token Fingerprint')),
                ('refresh_token_fingerprint', models.CharField(default='e99a18c428cb38d5f', max_length=64, unique=True, verbose_name='Refresh Token Fingerprint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Whitelist Token',
                'verbose_name_plural': 'User Whitelist Tokens',
                'ordering': ['user'],
            },
        ),
    ]
