# Generated by Django 5.2.8 on 2025-11-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(blank=type, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(blank=type, max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
