# Generated by Django 5.2.8 on 2025-11-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_usermodel_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('admin', 'SuperAdmin'), ('student', 'Student')], max_length=10, verbose_name='Role Name'),
        ),
    ]
