# Generated by Django 5.2.8 on 2025-11-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('admin', 'SuperAdmin'), ('student', 'Student')], default='admin', max_length=10, verbose_name='Role Name'),
        ),
    ]
