# Generated by Django 5.2.8 on 2025-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(choices=[(0, 'Super Admin'), (1, 'Student')], default=1, verbose_name='Role Name'),
        ),
    ]
