# Generated by Django 5.2.8 on 2025-12-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(choices=[(0, 'Super Admin'), (1, 'Student'), (2, 'Reviewer')], default=1, verbose_name='Role Name'),
        ),
    ]
