# Generated by Django 5.2.8 on 2026-02-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_usermodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
