# Generated by Django 5.2.8 on 2026-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_usermodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(choices=[(0, 'Super Admin'), (1, 'User')], default=1, verbose_name='Role Name'),
        ),
    ]
