# Generated by Django 5.2.8 on 2026-04-15 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_usermodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='parking_signs/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('summarize_message', models.TextField(blank=True, null=True)),
                ('park_status', models.BooleanField(blank=True, null=True)),
                ('detected_time', models.CharField(blank=True, max_length=50, null=True)),
                ('detected_day', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_parking_histories', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Parking History',
                'verbose_name_plural': 'Parking Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
