# Generated by Django 5.2.8 on 2026-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_userfcmtokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
