# Generated by Django 5.2.8 on 2026-04-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_usermodel_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinghistorymodel',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='User Feedback on Detection Accuracy'),
        ),
    ]
