# Generated by Django 5.2.8 on 2026-04-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_parkinghistorymodel_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='parking_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
