# Generated by Django 5.2.8 on 2026-04-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_usermodel_parking_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfcmtokenmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='parking_task_id',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(choices=[(0, 'Super Admin'), (1, 'Buyer'), (2, 'Seller'), (3, 'Leaser')], default=1, verbose_name='Role Name'),
        ),
        migrations.DeleteModel(
            name='ParkingHistoryModel',
        ),
        migrations.DeleteModel(
            name='UserFCMTokenModel',
        ),
    ]
