# Generated by Django 5.2.8 on 2026-04-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_usermodel_first_name_usermodel_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Super Admin'), (1, 'Buyer'), (2, 'Seller'), (3, 'Leaser')], null=True, verbose_name='Role Name'),
        ),
    ]
