# Generated by Django 5.2.8 on 2026-04-24 10:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_company_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.IntegerField(choices=[(1, 'Hotel'), (2, 'Resort'), (3, 'Villa'), (4, 'Service Apartment'), (5, 'Holiday Home')], default=1)),
                ('city', models.CharField(max_length=100)),
                ('full_address', models.TextField()),
                ('intent', models.IntegerField(choices=[(1, 'Sell'), (2, 'Lease'), (3, 'Both')], default=1)),
                ('expected_price_rent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rooms_keys', models.PositiveIntegerField(blank=True, null=True)),
                ('current_occupancy_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage from 0 to 100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
            },
        ),
        migrations.CreateModel(
            name='PropertyDocumentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_file', models.FileField(upload_to='property_documents/%Y/%m/')),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.propertylistingmodel')),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
            },
        ),
    ]
