# Generated by Django 5.2.8 on 2026-04-24 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistingmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='intent',
            field=models.IntegerField(choices=[(1, 'Sell'), (2, 'Lease'), (3, 'Both')]),
        ),
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='property_type',
            field=models.IntegerField(choices=[(1, 'Hotel'), (2, 'Resort'), (3, 'Villa'), (4, 'Service Apartment'), (5, 'Holiday Home')]),
        ),
    ]
