# Generated by Django 5.2.8 on 2026-05-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_propertyinquirymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertylistingmodel',
            old_name='current_monthly_income',
            new_name='annual_rental_income',
        ),
        migrations.RenameField(
            model_name='propertylistingmodel',
            old_name='rooms_keys',
            new_name='rooms',
        ),
        migrations.RemoveField(
            model_name='propertylistingmodel',
            name='current_occupancy_percent',
        ),
        migrations.RemoveField(
            model_name='propertylistingmodel',
            name='expected_price_rent',
        ),
        migrations.RemoveField(
            model_name='propertylistingmodel',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='propertylistingmodel',
            name='intent',
        ),
        migrations.AddField(
            model_name='propertylistingmodel',
            name='built_up_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Built-up Area in sq ft', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertylistingmodel',
            name='expected_monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='propertylistingmodel',
            name='listing_type',
            field=models.IntegerField(choices=[(1, 'Sell'), (2, 'Lease'), (3, 'Pre-Leased Sale')], default=1),
        ),
        migrations.AddField(
            model_name='propertylistingmodel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertylistingmodel',
            name='lock_in_period',
            field=models.PositiveIntegerField(blank=True, help_text='Lock-in period in months', null=True),
        ),
        migrations.AddField(
            model_name='propertylistingmodel',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylistingmodel',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='propertylistingmodel',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
