# Generated by Django 5.2.8 on 2026-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_current_monthly_income_propertylistingmodel_annual_rental_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistingmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending Approval'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
    ]
